version: '3'

services:
  api:
    image: customer
    ports: 
     - "8000:80"
    build:
      context: .
      dockerfile: API\Dockerfile

  webapi:
    image: webapi
    build:
      context: .
      dockerfile: WebApi\Dockerfile

